### ISSUE TITLE
rgw: resource execution failed: object upload failed

### ISSUE THREAD

**Issue by sunilkumarn417** [red-hat-storage/ceph-qe-scripts#23] opened 2020-04-09 06:11 UTC
``` 
Test data:
=============
       test: versioning_ops
        script: test_versioning_with_objects.py
        clients: ['client.0']
        config:
            local_file_delete: true
            user_count: 2
            bucket_count: 2
            objects_count: 50
            version_count: 5
            objects_size_range:
                min: 50
                max: 80
            test_ops:
                enable_version: true
                suspend_version: true
                copy_to_version: false
                delete_object_versions: false
                upload_after_suspend: true
```

```
2020-04-03 11:36:33,341.341 INFO:teuthology.orchestra.run.host018.stdout:args_val: ['/home/ubuntu/versioning_ops_1585920910_61/ceph-qe-scripts/rgw/v2/test_data/key.clarad.965.bucky-2790.0.43']
2020-04-03 11:36:33,342.342 INFO:teuthology.orchestra.run.host018.stdout:Resource Execution failed
2020-04-03 11:36:33,342.342 INFO:teuthology.orchestra.run.host018.stdout:Failed to upload /home/ubuntu/versioning_ops_1585920910_61/ceph-qe-scripts/rgw/v2/test_data/key.clarad.965.bucky-2790.0.43 to clarad.965.bucky-2790.0/key.clarad.965.bucky-2790.0.43: An error occurred (InternalError) when calling the CompleteMultipartUpload operation (reached max retries: 4): This multipart completion is already in progress
2020-04-03 11:36:33,342.342 INFO:teuthology.orchestra.run.host018.stdout:Resource execution failed: object upload failed
2020-04-03 11:36:33,342.342 INFO:teuthology.orchestra.run.host018.stdout:Traceback (most recent call last):
2020-04-03 11:36:33,342.342 INFO:teuthology.orchestra.run.host018.stdout:  File "ceph-qe-scripts/rgw/v2/tests/s3_swift/test_versioning_with_objects.py", line 135, in test_exec
2020-04-03 11:36:33,343.343 INFO:teuthology.orchestra.run.host018.stdout:    raise TestExecError("Resource execution failed: object upload failed")
2020-04-03 11:36:33,343.343 INFO:teuthology.orchestra.run.host018.stdout:v2.lib.exceptions.TestExecError: Resource execution failed: object upload failed
2020-04-03 11:36:33,343.343 INFO:teuthology.orchestra.run.host018.stdout:
```

**Comment by rakeshgm** [comment] 2020-04-09 06:21
The issue is seen when running tests on multiple-clients from teuthology

**Comment by rakeshgm** [comment] 2021-01-15 08:01
intermittent issue.

**Comment by rakeshgm** [comment] 2021-06-04 09:29
we have not seen this issue in the recent runs, so closing the ticket for now.

**Closed by rakeshgm** 2021-06-04 09:29 UTC
Labels: RGW
